"""
Typographus — WordPress publish connector.

Uses WordPress's own REST API (wp-json/wp/v2/posts) with an "Application
Password" — a WordPress core feature since 5.6, generated by the user in
their own wp-admin (Users → Profile → Application Passwords) specifically
to hand to third-party apps. It is NOT the user's real account password and
can be revoked independently at any time; Typographus never sees or stores
the real password.

Credentials are saved locally (same folder as the license token), never
inside a document's own JSON — so they don't get bundled into exports,
templates, or the "Pubblica nel Mondo" gallery.
"""
import json
import os
import urllib.error
import urllib.request
from base64 import b64encode

from . import license_manager as lic

_CRED_FILENAME = "wordpress.json"


def _cred_path() -> str:
    return os.path.join(lic.license_dir(), _CRED_FILENAME)


def get_credentials() -> dict:
    try:
        with open(_cred_path(), "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def has_credentials() -> bool:
    c = get_credentials()
    return bool(c.get("site_url") and c.get("username") and c.get("app_password"))


def save_credentials(site_url: str, username: str, app_password: str) -> bool:
    try:
        data = {
            "site_url": (site_url or "").strip().rstrip("/"),
            "username": (username or "").strip(),
            "app_password": (app_password or "").strip(),
        }
        with open(_cred_path(), "w", encoding="utf-8") as f:
            json.dump(data, f)
        return True
    except Exception:
        return False


def remove_credentials():
    try:
        os.remove(_cred_path())
    except Exception:
        pass


def check_site() -> dict:
    """Verifies the configured site actually is WordPress and reachable,
    without publishing anything — probes GET /wp-json/ (public, no auth)."""
    creds = get_credentials()
    site = creds.get("site_url")
    if not site:
        return {"ok": False, "error": "Nessun sito configurato."}
    try:
        req = urllib.request.Request(site + "/wp-json/", headers={"User-Agent": "Typographus/1.0"})
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode())
        name = data.get("name", "")
        return {"ok": True, "siteName": name}
    except urllib.error.HTTPError as e:
        return {"ok": False, "error": f"Il sito ha risposto con un errore ({e.code}). Non sembra WordPress, o l'API REST è disattivata."}
    except Exception as e:
        return {"ok": False, "error": f"Impossibile raggiungere il sito: {e}"}


def publish(title: str, html: str, status: str = "draft") -> dict:
    creds = get_credentials()
    site = creds.get("site_url")
    user = creds.get("username")
    app_pw = creds.get("app_password")
    if not (site and user and app_pw):
        return {"ok": False, "error": "Credenziali WordPress non configurate."}

    token = b64encode(f"{user}:{app_pw}".encode()).decode()
    body = json.dumps({"title": title, "content": html, "status": status if status in ("draft", "publish") else "draft"}).encode()
    req = urllib.request.Request(
        site + "/wp-json/wp/v2/posts",
        data=body,
        method="POST",
        headers={
            "Authorization": f"Basic {token}",
            "Content-Type": "application/json",
            "User-Agent": "Typographus/1.0",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            data = json.loads(resp.read().decode())
        return {"ok": True, "link": data.get("link", ""), "id": data.get("id")}
    except urllib.error.HTTPError as e:
        detail = ""
        try:
            detail = json.loads(e.read().decode()).get("message", "")
        except Exception:
            pass
        if e.code == 401:
            return {"ok": False, "error": "Autenticazione rifiutata: controlla utente e Password Applicazione."}
        return {"ok": False, "error": f"WordPress ha rifiutato la richiesta ({e.code}). {detail}"}
    except Exception as e:
        return {"ok": False, "error": f"Impossibile pubblicare: {e}"}
